### ISSUE TITLE
wails dev/build fails on clean cloned copy

### ISSUE THREAD

**Issue by portfolio-systems** [raguay/BulletinBoard#6]
Just clone this repo but cannot use.

Wails complains that frontend/dist is missing

... and it's true ...

**Comment by raguay** [comment]
Yes, because the initial build needs to be done first. You should:

1) go to the `frontend` directory and run these commands:
```sh
npm install
npm run build
```
2) After that, you can go back to the project directory and run the wails builder:
```sh
wails build --platform "darwin/universal"
```

Step 1 only needs to be done once. After that, step 2 will do everything needed. I'm not sure why the wails build isn't getting the first build right. It started messing up when I moved from Wails 1 to Wails 2.
